const TYPES = {
    INITIAL_FETCH: 'INITIAL_FETCH',
    LOAD_GOAL: 'LOAD_GOAL',
    FORM_UPDATE_BOOK: 'FORM_UPDATE_BOOK',
    FORM_UPDATE_GOAL: 'FORM_UPDATE_GOAL',
    ADD_BOOK: 'ADD_BOOK',
    REMOVE_BOOK: 'REMOVE_BOOK',
    SAVE_BOOK: 'SAVE_BOOK',
    TOGGLE_BOOK: 'TOGGLE_BOOK',
    
    SAVE_GOAL: 'SAVE_GOAL',
    
}

export default TYPES