const TYPES = {
    INITIAL_FETCH: 'INITIAL_FETCH',
    ADD_BOOK: 'ADD_BOOK',
    REMOVE_BOOK: 'REMOVE_BOOK',
    TOGGLE_BOOK: 'TOGGLE_BOOK',

    SAVE_GOAL: 'SAVE_GOAL',
    LOAD_GOAL: 'LOAD_GOAL',
    FORM_UPDATE_GOAL: 'FORM_UPDATE_GOAL',
}

export default TYPES