const TYPES = {
    SELECTED_BOOK: 'SELECTED_BOOK',
    NONE_SELECTED: 'NONE_SELECTED',
    INITIAL_FETCH: 'INITIAL_FETCH',
    FORM_UPDATE_BOOK: 'FORM_UPDATE_BOOK',
    FORM_UPDATE_GOAL: 'FORM_UPDATE_GOAL',
    NEW_BOOK: 'NEW_BOOK',
    ADD_BOOK: 'ADD_BOOK',
    REMOVE_BOOK: 'REMOVE_BOOK',
    UPDATE_BOOK: 'UPDATE_BOOK',
    SAVE_BOOK: 'SAVE_BOOK',
    TOGGLE_BOOK: 'TOGGLE_BOOK',
    
    SAVE_GOAL: 'SAVE_GOAL',
    
}

export default TYPES